#!/bin/sh

# TiogaPass UART routing for host SOL console.
# BIOS only outputs to COM0 (0x3F8); COM1 (0x2F8) is not used by BIOS.
# ASPEED crossbar routes BIOS output to ttyS3 via the transparent UART1 path:
#   BIOS COM0 TX -> LPC UART1 (transparent) -> crossbar uart4<-uart1 -> UART4 RX -> ttyS3
# Keyboard from SOL back to BIOS:
#   ttyS3 TX -> UART4 TX -> crossbar uart1<-uart4 -> LPC COM0 keyboard RX -> BIOS
#
# The crossbar configuration is volatile (reset on reboot) so it must be
# set here at service start. The HICRC register (0x1e789098 = 0x0A30) set
# in U-Boot provides LPC COM1->UART4 decode as a secondary path (read-only
# from Linux), but BIOS does not use COM1, so the crossbar path is primary.
#
# Note: when a SOL client connects, obmc-console forwards terminal init
# sequences (e.g. \x1b[?2004h) to ttyS3 TX which reach the BIOS COM0
# keyboard buffer. BIOS ignores unrecognized escape sequences during POST.

ROUTER=/sys/bus/platform/devices/1e78909c.uart-routing

setup() {
    # Disable kernel tty echo on ttyS3 before obmc-console-server opens it.
    stty -F /dev/ttyS3 raw -echo -echoe -echok -echonl 2>/dev/null || true

    # Route BIOS COM0 TX to ttyS3 (BIOS output -> SOL read path)
    echo uart1 > $ROUTER/uart4

    # Route ttyS3 TX to LPC COM0 keyboard (SOL keyboard -> BIOS)
    echo uart4 > $ROUTER/uart1

    # Chain uart3<-uart1 and uart2<-uart3 to match OEM crossbar state
    # (secondary path for physical pin output; harmless for software UARTs)
    echo uart1 > $ROUTER/uart3
    echo uart3 > $ROUTER/uart2

    hostserialcfg=$(fw_printenv hostserialcfg 2>/dev/null)
    hostserialcfg=${hostserialcfg##*=}

    if [ "$hostserialcfg" = 1 ]; then
        baud=921600
    else
        baud=115200
    fi

    echo "Configuring host UART ttyS3 for $baud baud"

    cat > /etc/obmc-console/server.ttyS3.conf <<-EOF
	# Autogenerated by $0
	baud = $baud
	console-id = default
	EOF
}

setup_routing() {
    # Called by obmc-console-server (meta-common patch) when a new SOL client
    # connects. Crossbar is already set in setup(); nothing more to do here.
    echo "UART crossbar active: uart4<-uart1 (BIOS->ttyS3), uart1<-uart4 (ttyS3->BIOS)"
}

teardown() {
    echo "SOL teardown: restoring default crossbar for uart1 and uart4"
    echo io1 > $ROUTER/uart1
    echo io4 > $ROUTER/uart4
}

$1
