#!/bin/sh

# TiogaPass UART routing for host SOL console.
# Host LPC COM1 (0x3F8) -> ASPEED SuperIO -> uart1 TX path in crossbar
# -> uart_routing: uart2 input = uart1 -> UART2 = /dev/ttyS1 -> obmc-console
# SuperIO enabled by CONFIG_ASPEED_ENABLE_SUPERIO=y in U-Boot (keeps HW_STRAP1 bit 20 clear).

ROUTER=$(echo /sys/bus/platform/drivers/aspeed-uart-routing/*.uart-routing 2>/dev/null)
[ -L "$ROUTER" ] || exit 2

route() {
    echo -n "$1" > "$ROUTER/$2"
    echo -n "$2" > "$ROUTER/$1"
}

setup_routing() {
    echo "Enabling UART routing: uart1 <-> uart2, uart4 <-> io1"
    route uart1 uart2
    route uart4 io1
}

setup() {
    setup_routing

    hostserialcfg=$(fw_printenv hostserialcfg 2>/dev/null)
    hostserialcfg=${hostserialcfg##*=}

    if [ "$hostserialcfg" = 1 ]; then
        baud=921600
    else
        baud=115200
    fi

    echo "Configuring host UART for $baud baud"

    cat > /etc/obmc-console/server.ttyS1.conf <<-EOF
	# Autogenerated by $0
	baud = $baud
	console-id = default
	EOF
}

teardown() {
    echo "Disabling UART routing"
    route uart1 io1
    route uart2 io2
    route uart4 io4
}

$1
