BBPATH =. "${LAYERDIR}:"

# Fix for meta-common being incomplete
BBFILES += " \
        ${TOPDIR}/meta-common/recipes-*/*/*/*.bb \
        ${TOPDIR}/meta-common/recipes-*/*/*/*.bbappend \
        ${TOPDIR}/meta-common/recipes-*/*/*/*/*.bbappend \
        ${TOPDIR}/meta-common/meta-common/recipes-*/*/*.bb \ 
        ${TOPDIR}/meta-common/meta-common/recipes-*/*/*.bbappend \
"

BBFILES += "${LAYERDIR}/recipes-*/*/*.bb \
            ${LAYERDIR}/recipes-*/*/*.bbappend \
            ${LAYERDIR}/meta-common/recipes-*/*/*.bb \
            ${LAYERDIR}/meta-common/recipes-*/*/*.bbappend \
"

BBFILE_COLLECTIONS += "flax"
BBFILE_PATTERN_flax = "^${LAYERDIR}/"
BBFILE_PRIORITY_flax = "20"


LAYERSERIES_COMPAT_flax = "scarthgap"
